
import java.sql.ResultSet;
import java.util.ArrayList;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import poliSiniflar.MySQLConnection;

/**
 *
 * @author Betül Akçay
 */
public class karsilamaEkrani extends javax.swing.JFrame {

    
    DefaultTableModel dt = new DefaultTableModel();
    ArrayList<String> list = new ArrayList<>();
     public karsilamaEkrani() {
        initComponents();
        
        dt.addColumn("ID");
        dt.addColumn("Müşteri Adı");
        dt.addColumn("Telefonu");
        dt.addColumn("Cihaz Adı");
        dt.addColumn("Cihaz Markası");
        dt.addColumn("Cihaz Modeli");
        dt.addColumn("Arızası");
        tabloDoldur();

        
    }
     public void tabloDoldur() {
         MySQLConnection db = new MySQLConnection();
        try {
            ResultSet rs = db.data("ariza inner join cihaz on cihaz.id = ariza.cihaz_id");
            while (rs.next()) {
                if(rs.getString("durum").equals("1")) {
                 list.add(rs.getString("id"));
                 dt.addRow(new String[]{rs.getString("id"), rs.getString("musteri_adi"), rs.getString("musteri_tel"), rs.getString("adi"), rs.getString("markasi"), rs.getString("modeli"), rs.getString("arizasi")});
            }
            }
        } catch (Exception e) {
        }
        tblListe.setModel(dt);
     }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        tblListe = new javax.swing.JTable();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        btn_ara = new javax.swing.JButton();
        txt_urunAra = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jButton4 = new javax.swing.JButton();
        btn_yenile = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        tblListe.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null}
            },
            new String [] {
                "id", "Müşteri Adı", "Telefonu", "Cihaz Adı", "Cihaz Markası", "Cihaz Modeli", "Arızası"
            }
        ));
        jScrollPane1.setViewportView(tblListe);

        jButton1.setText("Yeni Arıza Kaydı");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setText("Yeni Cihaz Kaydı");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        btn_ara.setText("Ara");
        btn_ara.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_araActionPerformed(evt);
            }
        });

        txt_urunAra.setText("Ürün Ara");

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel1.setText("Yetkli Servis Programı");

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel2.setText("Arızadaki Ürünler");

        jButton4.setText("Seçiliyi Arşive Gönder");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });

        btn_yenile.setText("Tablo Yenile");
        btn_yenile.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_yenileActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 607, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel1)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel2)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(btn_yenile)
                                .addGap(31, 31, 31)))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(jButton2)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jButton1))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(txt_urunAra)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(btn_ara))))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jButton4)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton1)
                    .addComponent(jButton2)
                    .addComponent(jLabel1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 44, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btn_ara)
                    .addComponent(txt_urunAra, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2)
                    .addComponent(btn_yenile))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 138, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton4)
                .addGap(8, 8, 8))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        cihazEkle cE = new cihazEkle();
        this.hide();
        cE.setVisible(true);
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        yeniArizaKaydi aK = new yeniArizaKaydi();
        this.hide();
        aK.setVisible(true);
    }//GEN-LAST:event_jButton1ActionPerformed

    private void btn_araActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_araActionPerformed
       dt.getDataVector().clear();
       tblListe.removeAll();
       
        String aranan = "";
        String gelen = txt_urunAra.getText();
        String[] dizi = gelen.split(" ");
        
        for(String item : dizi) {
            aranan += item + "*";
        }
        try {
            MySQLConnection db = new MySQLConnection();
            ResultSet rs = db.st.executeQuery("call fullTextAra('"+aranan+"')");
           // ResultSet rs = db.st.executeQuery("select * from ariza inner JOIN cihaz on ariza.cihaz_id = cihaz.id where Match (ariza.musteri_adi) AGAINST('"+aranan+"*' IN Boolean MODE)");
            while(rs.next()) {
                dt.addRow(new String[]{rs.getString("id"), rs.getString("musteri_adi"), rs.getString("musteri_tel"), rs.getString("adi"), rs.getString("markasi"), rs.getString("modeli"), rs.getString("arizasi")});
            }
           
            tblListe.setModel(dt);
        } catch (Exception e) {
        }
        
    }//GEN-LAST:event_btn_araActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        int secilenID = tblListe.getSelectedRow();
        String gtr = list.get(secilenID);
        System.out.println(gtr);
       
        
        MySQLConnection db = new MySQLConnection();
        try{
            int sonuc = db.dataUpdate("update ariza set durum = '"+0+"' where id = '"+gtr+"' ");
            if(sonuc > 0) {
                JOptionPane.showMessageDialog(this, "Arşive Eklendi");
                tblListe.removeAll();
                dt.getDataVector().clear();
                tabloDoldur();
            }
        } catch(Exception e) {
            
        }
       
    }//GEN-LAST:event_jButton4ActionPerformed

    private void btn_yenileActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_yenileActionPerformed
        dt.getDataVector().clear();
        tblListe.removeAll();
        tabloDoldur();
    }//GEN-LAST:event_btn_yenileActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(karsilamaEkrani.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(karsilamaEkrani.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(karsilamaEkrani.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(karsilamaEkrani.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new karsilamaEkrani().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_ara;
    private javax.swing.JButton btn_yenile;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton4;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tblListe;
    private javax.swing.JTextField txt_urunAra;
    // End of variables declaration//GEN-END:variables
}
